In [17]:
import random as random
import numpy as np
from numpy import *
from numpy.random import seed
from numpy.random import rand
seed(100)


##########Section below is the matrice generation section############
n=5
rows = []
 
for i in range (0,n+1):
    row_i = rand(n+1)
    row_i = row_i / row_i.sum()
    rows.append(row_i)
    
matrix = np.array(rows)
print ("initial matrix is:\n " ,matrix)
#####################################

##############Absorbing state matrix Generation################
"""
n=5
rows = []
 
for i in range (0,n):
    row_i = rand(n+1)
    row_i = row_i / row_i.sum()
    rows.append(row_i)
last_row = [0,0,0,0,0,1]
rows.append(last_row)
matrix = np.array(rows)
print ("initial matrix is:\n " ,matrix)"""

############# Section below is the part of Monte Carlo Simulation######################
M=0
selected_states=[]
zeroth = random.randint(0, n+1)
selected_states.append(zeroth)
print("initial state is\n ",zeroth)
while M< 200000:
    curr_state = selected_states[-1]
    prob = random.random()
    i = 1
    if prob > matrix[curr_state][0:n].sum():
        curr_state = n
    
    else:
        while n-i>=0:
            if prob> matrix[curr_state][0:n-i].sum():
                curr_state = n-i
                break
            else:
                i +=1
    selected_states.append(curr_state)
    M+=1

pi_i = []
for i in range(0,n+1):
    pi_i.append(selected_states.count(i)/M)   #### Counting and appending the total num of appearencies to the pi_i list.
print("pi'i values of the states obtained by Monte Carlo Simulation:\n ",pi_i)
#################################################################        


####################### Section below is the method of Matrix Maltuplication ##################
epsilon = 0.0005
condition = True
while condition:
    matrix = np.matmul(matrix,matrix)
    c=0
    for i in range(0,n+1):
        colmn_avg = matrix[:,i].sum()/(n+1)
        rndm_row = random.randint(0, n+1)
        if np.abs(matrix[rndm_row,i]- colmn_avg) < epsilon:
            c+=1
        else:
            break
    if c == n+1:
        condition=False
        
print("This the last of form of the matrix which has been multiplied by itself several times. Matrix Maltuplication Method:\n ",matrix)
########################################################################################
    
    


initial matrix is:
  [[0.24506887 0.12554113 0.19145216 0.38098353 0.00212815 0.05482616]
 [0.20270901 0.24958334 0.04131449 0.17380061 0.26936897 0.06322358]
 [0.07486041 0.04377714 0.08874334 0.39529965 0.32786661 0.06945286]
 [0.22573874 0.07579905 0.11939403 0.25997882 0.22613274 0.09295661]
 [0.10846051 0.23053104 0.00351734 0.1560813  0.4919773  0.00943252]
 [0.22886084 0.23075685 0.04018444 0.14596788 0.01394011 0.34028988]]
initial state is
  2
pi'i values of the states obtained by Monte Carlo Simulation:
  [0.185255, 0.160275, 0.082425, 0.245935, 0.24896, 0.077155]
This the last of form of the matrix which has been multiplied by itself several times. Matrix Maltuplication Method:
  [[0.18408017 0.1609747  0.08246506 0.24474951 0.25016023 0.07757033]
 [0.18402247 0.16105861 0.08239539 0.24466185 0.25042162 0.07744007]
 [0.18400842 0.16108374 0.08237647 0.24463709 0.25048798 0.07740629]
 [0.18404715 0.1610243  0.08242462 0.24469836 0.25031096 0.07749462]
 [0.1839498  0.16116788 